### ISSUE TITLE
Fatal error on start

### ISSUE THREAD

**Issue by Normolo** [IIcloudBob/StringRepeater#1]
Screenshot: 
![image](https://user-images.githubusercontent.com/53821637/113105235-a96c4600-9201-11eb-90e0-69bd856f030d.png)

**Comment by IIcloudBob** [comment]
> Screenshot:
> ![image](https://user-images.githubusercontent.com/53821637/113105235-a96c4600-9201-11eb-90e0-69bd856f030d.png)

Did you download all the files into a single folder? Just downloading the executable doesn't work

**Comment by Normolo** [comment]
Why not compile it into a `.msi` installer?

**Comment by IIcloudBob** [comment]
because it's a really small project and there is no need to. Just extract all the contents into a single folder

**Comment by Normolo** [comment]
Alright, also, I know this isn't a good place, but can ya look in DMs for a moment

**Comment by IIcloudBob** [comment]
I have a new account. weeeeeeeeeel#6671
I got locked out of my previous one
